[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/rose-pine-moon.toml"]

[window]
padding = { x = 10, y = 10 }
decorations = "Buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"
opacity = 0.75
blur = true

[font]
size = 16

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"


[keyboard]
bindings = [
  { key = "B", mods = "Control", chars = "\u001BB" }, # Ctrl + B (Move backward one word)
  { key = "F", mods = "Control", chars = "\u001BF" }, # Ctrl + F (Move forward one word)
]
