import = ["~/.config/alacritty/themes/rose-pine-moon.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
decorations = "Buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font"
size = 16
