"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_iris)\
$os\
$username\
[](bg:color_rose fg:color_iris)\
$directory\
[](fg:color_rose bg:color_gold)\
$git_branch\
$git_status\
[](fg:color_gold bg:color_iris)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_iris bg:color_subtle)\
$docker_context\
$conda\
[](fg:color_subtle bg:color_muted)\
$time\
[ ](fg:color_muted)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
# custom colors
color_rose = '#d7827e'
color_gold = '#ea9d34'
color_iris = '#907aa9'
color_foam = '#9ccfd8'
color_love = '#eb6f92'
color_pine = '#3e8fb0'
color_subtle = '#908caa'
color_muted = '#6e6a86'

[os]
disabled = false
style = "bg:color_iris fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_iris fg:color_fg0"
style_root = "bg:color_iris fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_rose"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_gold"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_gold)]($style)'

[git_status]
style = "bg:color_gold"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_gold)]($style)'

[nodejs]
symbol = ""
style = "bg:color_iris"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_iris)]($style)'

[c]
symbol = " "
style = "bg:color_iris"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_iris)]($style)'

[rust]
symbol = ""
style = "bg:color_iris"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_iris)]($style)'

[golang]
symbol = ""
style = "bg:color_iris"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_iris)]($style)'

[php]
symbol = ""
style = "bg:color_iris"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_iris)]($style)'

[java]
symbol = " "
style = "bg:color_iris"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_iris)]($style)'

[kotlin]
symbol = ""
style = "bg:color_iris"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_iris)]($style)'

[haskell]
symbol = ""
style = "bg:color_iris"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_iris)]($style)'

[python]
symbol = ""
style = "bg:color_iris"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_iris)]($style)'

[docker_context]
symbol = ""
style = "bg:color_subtle"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_subtle)]($style)'

[conda]
style = "bg:color_subtle"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_subtle)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_muted"
format = '[[  $time ](fg:color_fg0 bg:color_muted)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_rose)'
